import React, { useMemo } from 'react'
import * as THREE from 'three'
import { latToWorldZ, lonToWorldX } from '../lib/geo'
import { ROAD_STYLE, roadWidthFor, isPaintedRoad } from '../lib/roadStyle'
import { buildRoadSurface } from '../lib/roadSurface'

// The carriageway table now lives in lib/roadStyle.js so the non-rendering
// consumers (the parking planner, the Node repro harness) can import it too.
// Re-exported here because every existing caller imports it from './Roads'.
export { ROAD_STYLE, roadWidthFor }

/**
 * Renders the OSM network as a Kenney-styled street: tarmac + a raised kerb +
 * a sidewalk strip + painted markings, merged into one BufferGeometry per
 * layer (four draw calls total).
 *
 * The geometry is generated by lib/roadSurface.js from the same ROAD_STYLE
 * table the parking planner, the traffic-lane model and the drivable-surface
 * test all read, so the painted carriageway and the gameplay width can never
 * drift apart. See that module for why the Kenney road TILES are not used here
 * (they are a 1x1 m grid kit with baked markings and cannot follow real OSM
 * ways) — the real Kenney models are placed separately, in RoadFurniture.jsx.
 *
 * y offsets keep the layers separated: the sidewalks and kerbs are raised, so
 * they never z-fight with the tarmac they sit beside.
 */

/**
 * Real OSM street name for a road segment (or a whole road object): the
 * `name` tag when the way has one (map_data.json carries it — see
 * parse_map.py), `null` otherwise. NO road-class fallback ("Service Rd",
 * "Primary Link", ...) — StreetHUD shows road names + area names only
 * (area fallback: lib/worldData.areaLabels).
 */
export const streetLabelFor = (typeOrRoad) => {
  const name = typeof typeOrRoad === 'object' && typeOrRoad !== null ? typeOrRoad.name : null
  return typeof name === 'string' && name.trim() ? name.trim() : null
}

// The old three bucket ribbons (path/minor/major, each with its own colour and
// y offset) are GONE: the surface builder now emits a single layered street
// per way class instead, and the bucket colours had no other consumer.

/**
 * Publish the DRIVABLE road segments (world-space line segments + their width)
 * into `window.__gtathensRoadCache` for the driving surface model
 * (car-modules/crashManager.js `isOnAsphalt`): asphalt = full grip/top speed,
 * anything else = 0.55x (off-road drag). Footways/paths are skipped on purpose
 * — a 2 m footway is not a drivable surface, so counting it would hand cars
 * full speed on the pavement.
 *
 * One flat array of stable {ax, az, bx, bz, w, type, name} objects, built ONCE
 * per road data load; the consumer does a throttled point-segment test, so
 * nothing here runs per frame. `name` is the real OSM street name when the
 * way has one (see parse_map.py); unnamed ways carry name:null — the HUD
 * falls back to the area label (no road-class strings).
 */
export const publishRoadSegments = (roads) => {
  const segs = []
  for (const road of roads || []) {
    // Same predicate the parking planner's surface oracle uses: painted
    // carriageway only (path bucket / unknown types are not tarmac).
    if (!isPaintedRoad(road.type)) continue
    const w = roadWidthFor(road.type)
    for (let i = 0; i < (road.nodes || []).length - 1; i++) {
      const a = road.nodes[i]
      const b = road.nodes[i + 1]
      const ax = lonToWorldX(a.lon)
      const az = latToWorldZ(a.lat)
      const bx = lonToWorldX(b.lon)
      const bz = latToWorldZ(b.lat)
      // Skip zero-length stubs (they'd make a degenerate point-segment test).
      if (Math.abs(bx - ax) < 1e-6 && Math.abs(bz - az) < 1e-6) continue
      // `type` + `name` ride along so the street-name HUD can label the
      // nearest segment without a second OSM walk. `name` is the real OSM
      // street name when the way has one (see parse_map.py); unnamed ways
      // carry name:null — the HUD falls back to the area label, never to a
      // road-class string.
      segs.push({ ax, az, bx, bz, w, type: road.type, name: road.name ?? null })
    }
  }
  if (typeof window !== 'undefined') window.__gtathensRoadCache = { segs }
  return segs.length
}

/** OSM node -> world metres. Shared by the surface builder and the publisher. */
const toWorld = (n) => ({ x: lonToWorldX(n.lon), z: latToWorldZ(n.lat) })

/** Wrap a {positions, normals} soup in a BufferGeometry. */
const toGeometry = (soup) => {
  const g = new THREE.BufferGeometry()
  g.setAttribute('position', new THREE.Float32BufferAttribute(soup.positions, 3))
  g.setAttribute('normal', new THREE.Float32BufferAttribute(soup.normals, 3))
  // A merged network is not a closed solid, so a real bounding volume would be
  // computed once and then re-tested per frame; the old ribbons skipped it too.
  g.computeBoundingSphere()
  return g
}

const Roads = ({ roads }) => {
  const geos = useMemo(() => {
    const built = buildRoadSurface(roads, ROAD_STYLE, toWorld)
    return {
      tarmac: toGeometry(built.tarmac),
      pavement: toGeometry(built.pavement),
      kerb: toGeometry(built.kerb),
      walk: toGeometry(built.walk),
      paint: toGeometry(built.paint),
    }
  }, [roads])
  // Publish the drivable segment cache with the same data the surfaces are
  // built from, so the driving surface model always matches the VISIBLE
  // tarmac (isOnAsphalt, car grip, off-road drag).
  useMemo(() => publishRoadSegments(roads), [roads])

  return (
    <group>
      {/* Carriageway. The y lift keeps it above the ground plane (y=0) the way
          the old bucket ribbons did, and below the raised kerb/sidewalk.
          Asphalt, not black: a near-black tarmac reads as a void under a
          building's shadow, which is most of a street canyon. */}
      <mesh geometry={geos.tarmac} position={[0, 0.03, 0]} receiveShadow>
        <meshStandardMaterial color="#585c66" roughness={0.96} metalness={0} side={THREE.DoubleSide} />
      </mesh>
      {/* Footways / plazas. Same light concrete as the sidewalk strip, one
          material so the whole pavement system reads as one surface. */}
      <mesh geometry={geos.pavement} position={[0, 0.032, 0]} receiveShadow>
        <meshStandardMaterial color="#b9b4a6" roughness={0.98} metalness={0} side={THREE.DoubleSide} />
      </mesh>
      {/* Painted markings sit a hair above the tarmac. */}
      <mesh geometry={geos.paint} position={[0, 0.03, 0]}>
        <meshStandardMaterial color="#e8e4d8" roughness={0.85} metalness={0} side={THREE.DoubleSide} />
      </mesh>
      {/* Sidewalk: a light slab outboard of the kerb. */}
      <mesh geometry={geos.walk} position={[0, 0.05, 0]} receiveShadow>
        <meshStandardMaterial color="#b9b4a6" roughness={0.98} metalness={0} side={THREE.DoubleSide} />
      </mesh>
      {/* Kerb: the raised lip, which is what makes it read as a street rather
          than a decal, and the only layer that casts. */}
      <mesh geometry={geos.kerb} position={[0, 0.03, 0]} castShadow receiveShadow>
        <meshStandardMaterial color="#cfcabb" roughness={0.95} metalness={0} side={THREE.DoubleSide} />
      </mesh>
    </group>
  )
}

export default Roads
